apiVersion: openchoreo.dev/v1alpha1
kind: SecretReference
metadata:
  name: inventory-db-server
  namespace: default
spec:
  refreshInterval: 1h
  template:
    type: Opaque
  data:
    - secretKey: value
      remoteRef:
        key: inventory-db-server
---
apiVersion: openchoreo.dev/v1alpha1
kind: SecretReference
metadata:
  name: inventory-db-port
  namespace: default
spec:
  refreshInterval: 1h
  template:
    type: Opaque
  data:
    - secretKey: value
      remoteRef:
        key: inventory-db-port
---
apiVersion: openchoreo.dev/v1alpha1
kind: SecretReference
metadata:
  name: inventory-db-user
  namespace: default
spec:
  refreshInterval: 1h
  template:
    type: Opaque
  data:
    - secretKey: value
      remoteRef:
        key: inventory-db-user
---
apiVersion: openchoreo.dev/v1alpha1
kind: SecretReference
metadata:
  name: inventory-db-password
  namespace: default
spec:
  refreshInterval: 1h
  template:
    type: Opaque
  data:
    - secretKey: value
      remoteRef:
        key: inventory-db-password
---
apiVersion: openchoreo.dev/v1alpha1
kind: SecretReference
metadata:
  name: inventory-db-name
  namespace: default
spec:
  refreshInterval: 1h
  template:
    type: Opaque
  data:
    - secretKey: value
      remoteRef:
        key: inventory-db-name
